### ISSUE TITLE
[v4] --color flag not working well with webpack 4

### ISSUE THREAD

**Issue by SevenOutman** [webpack/webpack-cli#1967]
**Describe the bug**

I'm using `webpack-cli@4.0.0` with `webpack@4.44.2`. Running `webpack --progress --color` command does not output colorful log but plain text with no colors. 

However, `webpack serve` outputs with color normally.

**Screenshots**

![image](https://user-images.githubusercontent.com/8225666/96396102-eebf2d00-11f8-11eb-972b-d8f0ef215882.png)

**Please paste the results of `webpack-cli info` here, and mention other relevant information**
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 2.15 GB / 32.00 GB
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 86.0.4240.80
    Safari: 14.0
  Packages:
    clean-webpack-plugin: ^3.0.0 => 3.0.0 
    copy-webpack-plugin: ^6.2.1 => 6.2.1 
    css-minimizer-webpack-plugin: ^1.1.5 => 1.1.5 
    html-webpack-plugin: ^4.5.0 => 4.5.0 
    terser-webpack-plugin: ^4.2.3 => 4.2.3 
    webpack: ^4.44.2 => 4.44.2 
    webpack-cli: ^4.0.0 => 4.0.0 
    webpack-dev-server: ^3.11.0 => 3.11.0 
    webpack-merge: ^5.2.0 => 5.2.0 
```

**Comment by anshumanv** [comment]
Hi, it was a bug in CLI which is fixed here - https://github.com/webpack/webpack-cli/pull/1944

Should be out in the next release :)

**Comment by evilebottnawi** [comment]
Fixed in master, release will be today

**Comment by keyrox** [comment]
> Fixed in master, release will be today

Was it released? Still having the same issue.

**Comment by evilebottnawi** [comment]
You should not use `color` option, it was removed

**Comment by keyrox** [comment]
> You should not use the `color` flag, it was removed, we automatically enable/disable it if colors supported

I am using:
```
"webpack": "4.44.2"
"webpack-cli": "4.1.0"
```

And even without the `color` flag, it still doesn't show any colour.
When downgrading to "webpack-cli":"3.3.12" everything shows up with colours as usual.

**Comment by evilebottnawi** [comment]
please create reproducible test repo, it was fixed in 4.1.0
