### ISSUE TITLE
[Bug]: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by jesperlandmer** [webpack/webpack-cli#299]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Whenever I try to run `webpack`, I get this error message:

```
`vagrant@vagrant-ubuntu-trusty-32:/vagrant$ webpack
/usr/lib/node_modules/webpack-cli/bin/webpack.js:237
                                throw err;
                                ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/vagrant/webpack.config.tsx:1:77)
    at Module._compile (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (/usr/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/usr/lib/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/usr/lib/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /usr/lib/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/usr/lib/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/usr/lib/node_modules/webpack-cli/bin/webpack.js:234:39)
    at Object.parse (/usr/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:539:18)
    at /usr/lib/node_modules/webpack-cli/bin/webpack.js:212:8
    at Object.<anonymous> (/usr/lib/node_modules/webpack-cli/bin/webpack.js:504:3)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:643:30)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using Vagrant, and just installed webpack and webpack cli globally.
Using:

node.js: v8.9.4
npm: v5.6.0
webpack: v4.0.1
webpack-cli: v2.0.9

**What is the expected behavior?**
To bundle the files

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
I'm using Typescript and React on a Node machine. Vagrant runs on Ubuntu

**Comment by andriibyk-apiko** [comment]
I have a similar problem:

**TypeError: Cannot read property 'presetToOptions' of undefined**

Described by someone else on [StackOverflow](https://stackoverflow.com/questions/49035267/typeerror-cannot-read-property-presettooptions-of-undefined-in-webpack-cli-wi)

**Comment by ev1stensberg** [comment]
@andriibyk-apiko what version are you on?

**Comment by andriibyk-apiko** [comment]
@ev1stensberg 

```
"webpack": "^4.0.1",
"webpack-cli": "^2.0.9"
```

**Comment by ev1stensberg** [comment]
Mind printing your `prefix` paths?

**Comment by ev1stensberg** [comment]
Could you do a console log before the error throws on webpack?

**Comment by jesperlandmer** [comment]
Also hade the problem with "presetToOptions", but then I reinstalled webpack and then I got this error instead. Installed Webpack v.^2.0.0 instead and now it works

**Comment by ev1stensberg** [comment]
`npm config get prefix`

**Comment by andriibyk-apiko** [comment]
> Mind printing your `prefix` paths?

`/usr`

**Comment by ashclarke** [comment]
> Mind printing your `prefix` paths?

`C:\Users\<user>\AppData\Roaming\npm`

**Comment by ev1stensberg** [comment]
This might be hard for me to reproduce, anyone from @webpack/core-team that can?

**Comment by ashclarke** [comment]
@ev1stensberg - Not sure it helps, but it seems to only affect the global install.

I installed webpack-cli locally and it works, but you get the "prefer global" warning.

**Comment by imjar** [comment]
use
$ webpack-cli init

**Comment by ev1stensberg** [comment]
@ashclarke that might be cause our prefer to global is wrong ( I think ), will investigate.

**Comment by dhruvdutt** [comment]
@jesperlandmer @ashclarke Can you output `npm root -g`?

Related PR #332.

**Comment by d0as8** [comment]
What is the decision of issue?
(use webpack-cli 2.0.9 and webpack 4.1.1 global)

**Comment by ashclarke** [comment]
@dhruvdutt - `C:\Users\<user>\AppData\Roaming\npm\node_modules`

**Comment by ev1stensberg** [comment]
Can you try updating?

**Comment by QuantumInformation** [comment]
Not sure if this is realted, but if you run `npm i` here https://github.com/quantumjs/solar-popup/tree/master/demo

Then run `webpack-cli` I get
/Users/nikos/.nvm/versions/node/v9.2.0/lib/node_modules/webpack-cli/bin/webpack.js:242
                                throw err;
                                ^

Error: Cannot find module 'webpack'

**Comment by dhruvdutt** [comment]
@QuantumInformation You missed installing `webpack-cli`. Just do `npm i -D webpack-cli` inside your demo dir and you're set. :100:

**Comment by QuantumInformation** [comment]
Thx, I now get errors I haven't seen before

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment. 

ERROR in ../src/SolarPopup.ts
Module not found: Error: Can't resolve 'postcss-loader' in '/Users/nikos/WebstormProjects/solar-popup/demo'
 @ ../src/SolarPopup.ts 3:0-27
 @ ./index.ts

ERROR in ../src/ModalBackground.ts
Module not found: Error: Can't resolve 'postcss-loader' in '/Users/nikos/WebstormProjects/solar-popup/demo'
 @ ../src/ModalBackground.ts 2:0-32
 @ ../src/SolarPopup.ts
 @ ./index.ts

ERROR in ../src/SolarPopup.ts
Module not found: Error: Can't resolve 'vanilla-typescript' in '/Users/nikos/WebstormProjects/solar-popup/src'
 @ ../src/SolarPopup.ts 2:0-46 72:34-42
 @ ./index.ts

ERROR in [at-loader] ../src/SolarPopup.ts:2:58 
    TS2307: Cannot find module 'vanilla-typescript'.

**Comment by QuantumInformation** [comment]
Many thanks for this!

**Comment by ematipico** [comment]
Is this still valid?

**Comment by dhruvdutt** [comment]
@ematipico The PR has already merged and issue is resolved.

**Comment by ev1stensberg** [comment]
Friendly ping @jesperlandmer

**Comment by jesperlandmer** [comment]
Don’t know! I think the main issue has to do with Vagrant and how Vagrant handles global values. I had several problems with other dependencies as well (e.g. Firebase). Staying with docker from now on

**Comment by guahanweb** [comment]
@ev1stensberg and @jesperlandmer, I'm having the same error when I try to run webpack-cli within a docker container. Oddly enough, the error is:
```
Error: Cannot find module 'WEBPACK'
  ...
  at /usr/local/lib/node_modules/webpack-cli/bin/webpack.js:15:3
  at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:512:3
```

In my case, I am actually installing `webpack` and `webpack-cli` globally within the container as a precaution (issue started when referencing the locally installed `./node_modules/.bin/webpack` binary). I have both installed globally on my machine, and it seems to work fine. Not sure where the disconnect is. Here's the important bits of what's running inside my Dockerfile:

```
RUN npm i webpack webpack-cli -g

WORKDIR /app
COPY app /app
RUN npm i && npm run build
```

My build script is just running `webpack`, and I have tried referencing the executable globally as well as directly within the node_modules with the same issue.

Any thoughts would be awesome.

I'm am running the following versions:
```
"webpack": "^4.1.1",
"webpack-cli": "^2.0.12"
```

**Comment by okonet** [comment]
Same issue with the global install.

`npm install -g webpack-cli` and running `webpack-cli` throws:

```
•100% ➜ webpack-cli
/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:242
				throw err;
				^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/convert-argv.js:7:24)
    at Module._compile (/usr/local/lib/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at yargs.parse (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:239:14)
    at Object.parse (/usr/local/lib/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /usr/local/lib/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

**Comment by okonet** [comment]
Actually happens with the local setup as well:

`npm install --dev webpack-cli` and `webpack-cli` throws

```
•100% ➜ webpack-cli
undefined
/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/webpack.js:242
				throw err;
				^

TypeError: validateSchema is not a function
    at processConfiguredOptions (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/convert-argv.js:156:48)
    at module.exports (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/convert-argv.js:150:10)
    at yargs.parse (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/webpack.js:239:39)
    at Object.parse (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/node_modules/yargs/yargs.js:543:18)
    at /Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/webpack.js:512:3)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3
```

I think it's related to the webpack version. I'm installing CLI to migrate the project from 1.x to 4.x and I see this

`warning " > webpack-cli@2.0.13" has incorrect peer dependency "webpack@^4.0.0".`

I'm not sure why it is even installing it in this case...

**Comment by okonet** [comment]
Downgrading to `1.x` doesn't help either:

`npm install --dev webpack-cli@1.x && webpack-cli` throws:

```
•100% ➜ webpack-cli
module.js:545
    throw err;
    ^

Error: Cannot find module 'webpack/lib/ErrorHelpers'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/okonet/Projects/kleiner_perkins/crm_web_client/node_modules/webpack-cli/bin/webpack.js:11:20)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
```

**Comment by dhruvdutt** [comment]
What environment is it? I can't reproduce it locally. :thinking: 

Also, make sure when you do `webpack-cli --dev`, you run it with `npx webpack-cli` else it might get resolved from your global node_modules.

**Comment by okonet** [comment]
@dhruvdutt the problem goes away after upgrading webpack to 4 (I guess anything greater than 1).

**Comment by okonet** [comment]
@dhruvdutt I just tried with `npm` and webpack@4 installed:

```
npx webpack-cli migrate ./webpack/homebase/webpack.development.js 
npx: installed 489 in 19.386s
Cannot find module 'webpack'
```

**Comment by dhruvdutt** [comment]
Can you make a reproducible demo(zip) along with steps?
I think there's something wrong with the installation or running of commands.

**Comment by JonathanZWhite** [comment]
@okonet @dhruvdutt I'm running into this issue as well.

```
Cannot find module 'webpack'
```

It seems this issue is caused by `webpack.development.js` not being able to find my local `npm_modules` version of `webpack`. I think this is the case because when I run `webpack` without `--config` it runs, although it does throw an unrelated compile error. However, when I look in `node_modules` `webpack` is missing, despite running `npm install webpack -D`.

**Comment by ev1stensberg** [comment]
Maybe something fishy with how the cli resolves, I'll check it out

**Comment by Thommas** [comment]
Same problem here on Ubuntu 17. Should we install locally instead of globally ? Might be the temporary fix...

**Comment by ev1stensberg** [comment]
Could you try to install `webpack-cli@2.0.14`? Does the error persist?

**Comment by ev1stensberg** [comment]
`npx webpack` or CLI doesn't work, maybe @zkat has some tips regarding using IIFE & prefering locally installed packages?  The error is from here: https://github.com/webpack/webpack-cli/blob/master/bin/webpack.js#L11-L15

**Comment by darrenparkinson** [comment]
I was having the same issue in Docker, but only on Mac and Linux.  Windows was fine.  

As a temporary fix, I have had to add webpack and webpack-cli to the "dependencies" section in package.json (rather than just the devDependencies section).

I tried many different combinations in the dockerfile to install webpack during the build, but none of them worked except for this.

**Comment by pmaher** [comment]
I was getting the same error described in the initial comment.  (I'm using a mac with webpack version ^4.5.0 and webpack-cli version ^2.0.14)

I tried a few things all of which didn't work for me:
1) Used the global version of webpack + webpack-cli (uninstalling the local copies)
2) Adding webpack + webpack-cli  to the "devDependencies" section of my package.json and uninstalling the global versions.
3) Adding webpack + webpack-cli  to the "dependencies" section of my package.json and uninstalling the global versions. 

Ultimately, I managed to get around the issue with the following steps:
1) I uninstalled node completely, then reinstalled it again - version 9.11.1
2) I added webpack + webpack-cli to the "dependencies" section of my package.json.
3) I removed these lines from my webpack.config.js:  
    devServer: { hot: true },
    plugins: [ new webpack.HotModuleReplacementPlugin() ]
4) I now bundle my project with webpack by using the local version with the following command in the root directory of my project:
node_modules/.bin/webpack

**Comment by tony** [comment]
I had this happen, similar to the experience here: https://github.com/webpack/webpack-cli/issues/299#issuecomment-376839242

I use yarn. And yarn workspaces.

But the gist of it is I made sure webpack and webpack-cli were both in package.json. 4.5.0 and 2.0.14 worked for me. Locally installed (not ``npm i -g``)

I invoke webpack via ./node_modules/.bin/webpack (normal for me, since 3.x)

And, when this error happened, I just ``rm -rf node_modules`` (in all descendant workspace projects, too. e.g. ``rm -rf ./workspacea/node_modules``) and reinstalled again via ``$ yarn``. This wiped away whatever cruft was there before. That's what made it work for me.

Also if you're trouble shooting, double check to make sure you pick one or the other: a locally installed webpack+webpack-cli, or a system one. If you go local, sure you wipe out ``[sudo] npm uninstall -g webpack webpack-cli``.

(I still don't know whether it's best / wrong / right to use webpack on system's node_modules or local.)

**Comment by cloakedninjas** [comment]
Ran into this myself just now, none of the comments above have helped... Looking for clarification...

- Is `-g` not recommended ?

```
npm uninstall -g webpack webpack-cli
npm install -g webpack webpack-cli
webpack

Error: Cannot find module 'webpack'
```

**Comment by ev1stensberg** [comment]
Webpack-cli will try to default to your local installation, which makes the error appear. I'll try to push a fix to this as soon as possible.

**Comment by ajmald** [comment]
I just did npm install and it worked for me
I previously did updated my node and npm, here’s my configuration

Ajmals-MacBook-Pro:React ajmal$ node -v
v9.11.1
Ajmals-MacBook-Pro:React ajmal$ npm -v
5.8.0
Ajmals-MacBook-Pro:React ajmal$ webpack -v
4.5.0
Ajmals-MacBook-Pro:React ajmal$ webpack-cli -v
2.0.14

Ajmals-MacBook-Pro:React ajmal$ **npm install**

> fsevents@1.1.3 install /Users/ajmal/Desktop/Development/React/node_modules/fsevents
> node install

[fsevents] Success: "/Users/ajmal/Desktop/Development/React/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node" is installed via remote
npm WARN webpackdemo@1.0.0 No repository field.

added 405 packages from 314 contributors in 12.995s
Ajmals-MacBook-Pro:React ajmal$ webpack
Hash: d2bfce464a0dbc699c10
Version: webpack 4.5.0
Time: 363ms
Built at: 2018-4-16 14:07:18
        Asset      Size  Chunks             Chunk Names
script.min.js  4.71 KiB       0  [emitted]  main
Entrypoint main = script.min.js
   [0] ./js/scripts.js 0 bytes {0} [built]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

**Comment by ev1stensberg** [comment]
@ajmald Works when you don't sandbox the cli or webpack. Problems are when combined with other tools that rely on symlinks. As mentioned previously, we have an IIFEE for the entire bin file in order to use return inside it without exiting the process. 

I'll try to find out what we need to change in order to fix the issue, might take a couple of days though.

**Comment by ev1stensberg** [comment]
Anyone here having a confident reproduction of this error? Could you give me a repository?

**Comment by enobrev** [comment]
As per @tony 's comment, moving to [yarn workspaces](https://yarnpkg.com/lang/en/docs/workspaces/) fixed this issue for me.

Unfortunately the project I was seeing this issue with is not public, so I have no way of sharing, but I can describe it somewhat.  My project has the following structure:

```
project-folder/public/www
project-folder/public/manage
project-folder/other_stuff..
```

`www` and `manage` are both separate javascript (react) projects with their own `webpack.config.x.js` files and their own `package.json` files.  Up until recently, that hasn't been an issue, but today when I tried to build either one, I was getting the error in this issue in both folders

I did as described in the yarn workspaces doc, and then ran webpack-cli again and it worked just fine for both.

_As a side-note for anyone trying the same, I had to move postcss.config.js to my yarn workspace root.  Having it in each workspace (each subdirectory) was throwing all sorts of errors for me.  Also, the `workspaces` property in the root's `package.json` file have to be named after the subdirectories, not after the subdirectory `package.json` `name` properties_

**Comment by ev1stensberg** [comment]
Thanks for the info @enobrev , I'll check it out to see if we can fix the issue! Gonna look into it tomorrow

**Comment by ev1stensberg** [comment]
Could anyone try to run this branch locally in their project? #423 Also, it would be nice if you'd post a path to webpack by adding a `console.log` here https://github.com/webpack/webpack-cli/blob/836bfae8a0a3a5033576eb47d846509a3cea4e2c/bin/webpack.js#L427

**Comment by ev1stensberg** [comment]
Thanks for proividing @klick-barakgall !

**Comment by trammel** [comment]
Thanks @klick-barakgall I was getting the same error, and your explanation solved it for me also.

**Comment by klick-barakgall** [comment]
@ev1stensberg Sorry, but I feel that based on my findings that something is still wrong with webpack-cli. Is this a known issue? Is it being tracked elsewhere? Will you consider reopening this issue?

**Comment by ev1stensberg** [comment]
@klick-barakgall yep, it's this one

**Comment by klick-barakgall** [comment]
@ev1stensberg, apologies I see now this issue is in fact still open. My bad :S.

**Comment by thanhdungfb** [comment]
I have the same problem
And this command works with me: 
      npm uninstall -g webpack webpack-cli
      npm install -g webpack webpack-cli

**Comment by akolliy1** [comment]
I have run webpack several times on my project but suddenly throw this Error I tried to install babel-preset-react but throw Error.
Then, i run webpack in project it throws this Error below

module.js:540
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Program Files\nodejs\node_modules\webpack-dev-server\lib\Server.js:22:17)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! more-recipe-server@1.0.0 start: `webpack-dev-server --mode development --open`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the more-recipe-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\duntu\AppData\Roaming\npm-cache\_logs\2018-05-18T18_41_35_681Z-debug.log

**Comment by ev1stensberg** [comment]
This is probably fixed in #453, thanks for the patience guys ❤️ Closing for now. We're releasing a new version of webpack-cli in a bit, so keep tight, the bug is soon gone 😃

**Comment by rifler** [comment]
Any news? Still fails in 3.0.8

**Comment by ematipico** [comment]
Do you have a repository where we can check why it's falling? It might be better to open a new issue. This has been closed for a month so we assumed everything was patched. Maybe the issue is caused by something else. If you could open a new issue and provide a valid repro, it will be awesome. Thanks!

**Comment by rifler** [comment]
It is private, but this changes fixed this issue for me
```diff
  "scripts": {
-    "webpack": "webpack --config='config/webpack.config.js'",
+    "webpack": "webpack-cli --config='config/webpack.config.js'",
```

**Comment by ev1stensberg** [comment]
Strange. Do you have webpack installed already? try to only have a local installation

**Comment by kaushalyap** [comment]
I do still get the following the following:
`/node_modules/webpack-cli/bin/cli.js:244
				throw err;
				^
`
in **"webpack-cli": "^3.0.8"**. I tried @rifler solution it also does not work for me.

**Comment by ev1stensberg** [comment]
Install webpack and webpack-cli in pkg json and your scripts should call webpack on `webpack-cli@latest` and `webpack v4+`

**Comment by giandalpont** [comment]
Install webpack-cli and  yarn add 
npm install webpack-cli -D
yarn add webpack-cli  -D

**Comment by preston206** [comment]
probably covered already, but just in case... I'm a new webpack user and I installed webpack globally via npm and I installed webpack-cli within my local project's package.json dependencies. That is when the error was occurring. I uninstalled the local cli and then installed the cli globally. No more error. I think they both need to be in the same environment. This thread helped me figure it out. Thanks!

**Comment by ev1stensberg** [comment]
@preston206 Thanks for sharing. It's quite unfortunate for us that users hit this error though, we use `import-local` which should resolve this, but it doesn't as webpack and webpack-cli is in two different locations

**Comment by leechao** [comment]
I have the same problem. 
I have uninstalled globally webpack and webpack-cli
Here are the versions I use in my project package.json
`   "webpack": "^4.16.2",
    "webpack-cli": "^3.1.0",
`

And I still encounter the error whenever i run "npx webpack" or "npx webpack-cli"

`Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require `(internal/modules/cjs/loader.js:637:17)`

Any other solutions available ?

**Comment by ev1stensberg** [comment]
Doing a refactor of the bin folder and that will solve it. Ready in august/september!

**Comment by nebrelbug** [comment]
@ev1stensberg any progress? Installing webpack and webpack-cli locally doesn't work for me, and neither does `npx webpack` or running `webpack-cli`, and I tried `rm -rf node_modules` and then reinstall.

**Comment by nebrelbug** [comment]
I uninstalled globally `webpack` and `webpack-cli` and then reinstalled, and it seems to be working so far...

**Comment by ev1stensberg** [comment]
Working on fixing this but haven’t had a lot of spare time lately. Sorry for the inconviniences.. 👨🏼‍🔧

**Comment by nebrelbug** [comment]
@ev1stensberg in the meantime, what should I do to follow best practices with my projects?

**Comment by ev1stensberg** [comment]
Anything that runs webpack is viable. Ideal case is to run it through node modules by installing them both locally as devDeps. If that doesn’t work, then look in the issue thread 🤗

**Comment by vascofernandes** [comment]
got the same issue.

**Comment by twentytwokhz** [comment]
> @QuantumInformation You missed installing `webpack-cli`. Just do `npm i -D webpack-cli` inside your demo dir and you're set. 💯

Many thanks, it worked!

**Comment by TENsaga** [comment]
OP appears to be using Unix, but I had the same error after multiple project restarts/npm installs. For those using WSL / Bash for Windows I noticed sometimes `npm install` fails to install some of the binaries. Webpack and webpack-dev-server were missing in my case.

```
ls node_modules/.bin/  

// if the binaries are missing run any combo of:
npm i -D webpack webpack-cli webpack-dev-server 

// we had to modify our package.json to access the binary with the full path (instead of just webpack):
build:dev: "npx **./node_modules/.bin/webpack** --config ./webpack.config/service.dev.js --watch",
```

Spent half a day trying to figure this out, hopefully it helps someone.

**Comment by hazone** [comment]
I only got it to work by first install npm install -g webpack-cli and then npm install -g webpack.

**Comment by yvonnendutaw** [comment]
> I only got it to work by first install npm install -g webpack-cli and then npm install -g webpack.

Thanks! This worked for me too!

**Comment by gogromat** [comment]
Note: installing webpack globally is not [recommended](https://webpack.js.org/guides/installation/#global-installation).
For now I reference it as ```node_modules/webpack/bin/webpack.js``` in ```package.json/scripts``` section

**Comment by mosesnova** [comment]
npm i -D webpack-cli Worked for me.

**Comment by Jack85** [comment]
Same issue, deleting node_modules and package.lock worked for me
  - thnx to th3n3wguy and refenced issue 
https://github.com/vuejs/vue-cli/issues/2548#issuecomment-423593100

**Comment by TCarmine** [comment]
> I only got it to work by first install npm install -g webpack-cli and then npm install -g webpack.

This worked for me in the way that it then did found finally the webpack-cli module but then I got this warnings and error: 

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in multi ./app.js bundle.js
Module not found: Error: Can't resolve 'bundle.js' in '/home/carmine/Desktop/JS/webpack_app'
 @ multi ./app.js bundle.js main[1]

**Comment by TCarmine** [comment]
I solved my last issue thanks to this : https://stackoverflow.com/questions/49389677/module-not-found-error-cant-resolve-bundle-js-in-users-jonathankuhl-docum

**Comment by dupls** [comment]
You can try running webpack directly from the node_modules folder, this seems to solve a lot of the red errors in the terminal.

`./node_modules/.bin/webpack`

**Comment by willdonner** [comment]
npm link webpack
https://stackoverflow.com/questions/29492240/error-cannot-find-module-webpack

**Comment by cabello** [comment]
I likely cannot provide much insight but this was affecting me not locally on macOS but on my continuous integration provider linux/Ubuntu, after debugging with SSH in the CI, I found out that webpack-cli 3.2.0 was the first version to introduce this issue, so I downgraded it to 3.1.2 in my `package.json`:

```diff
- "webpack-cli": "3.2.0",
+ "webpack-cli": "3.1.2",
```

And it worked! I also tried many webpack 4.X and they all seemed to work with cli 3.1.2.

---

CI debugging data:
```
Docker Engine Version: 18.09.1
Kernel Version: Linux 31e94c1fa4b9 4.15.0-1035-aws #37-Ubuntu SMP Mon Mar 18 16:15:14 UTC 2019 x86_64 Linux
Starting container node:10.12.0
```

**Comment by evenstensberg** [comment]
Have you tried updating to the latest CLI version? Is the issue still persistent?

**Comment by cabello** [comment]
Yes, i also tried the latest version, forgot to mention it.

**Comment by evenstensberg** [comment]
Alright. Aware this is a bug, but the bug is due the fact that you have a global and a local installation or vice versa. Could you try aligning CLI installation location with webpack location?

**Comment by heldrida** [comment]
Hey, got a new machine and I don't have webpack and webpack-cli installed globally; Debugging at the moment but seems that the reports above are correct, the bug still persists; I'll update the comment with more info after I fully understand what's going on.

The following is for a project that has a dependecy 
```
devDependecies: {
    "foobar": "git+https://gitlab+deploy-token-1:xxxxx@yyyyyy/foobar.git#vTag",
}
```
```

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at runCommand.then (/Users/punkbit/www/temp1/node_modules/webpack/bin/webpack.js:142:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7) code: 'MODULE_NOT_FOUND' }

```
npm list -g --depth 0:

├── gatsby-cli@2.7.2
└── npm@6.4.1

Decided to cd into node_modules/foobar and tried:

npx webpack -v

One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no):

During npm install outside the node_modules/foobar I do get "One CLI for webpack must be installed...", which I accept but in the end there's the error I've reported earlier or at the top.

**Comment by tkdphoenix** [comment]
https://github.com/webpack/webpack-cli/issues/299#issuecomment-472690048
This worked for me. Once I ran `npm link` on webpack and webpack-cli it worked after that. No need to not follow best practice and install globally.

**Comment by MilanP28** [comment]
Link globally installed package to your project

npm link webpack

Full Code [Here](https://icetutor.com/question/error-cannot-find-module-webpack/)

**Comment by kironalp** [comment]
npm link

Try This If It Is Work

[Here](https://icetutor.com/question/error-cannot-find-module-webpack/) Is Solution With Example

**Comment by monu2580** [comment]
i was getting the same error " [Bug]: Cannot find module 'webpack' "
i fixed this Error after following these steps:
Step-1: Run this command to install webpack
      
     npm install --save-dev webpack webpack-cli
Step-2: uninstall Webpack
       
     npm uninstall --save-dev webpack webpack-cli
step-3: Delete node-module folder from your project directory 
    
     rm -rf node_modules
step-4: Run npm install
     
     npm install
step-5: Run yarn command

     yarn
step-6: Run start command

    yarn  start
or
   
    npm start

This is working for me

**Comment by monu2580** [comment]
![Screenshot from 2019-11-28 11-11-19](https://user-images.githubusercontent.com/30049228/69780696-fbe2c000-11d1-11ea-8791-afe744702e04.png)
![Screenshot from 2019-11-28 11-14-26](https://user-images.githubusercontent.com/30049228/69780698-fc7b5680-11d1-11ea-949b-5925b6c8a3b8.png)
![Screenshot from 2019-11-28 11-14-48](https://user-images.githubusercontent.com/30049228/69780700-fc7b5680-11d1-11ea-9dee-b003a955fa83.png)
![Screenshot from 2019-11-28 11-16-56](https://user-images.githubusercontent.com/30049228/69780701-fd13ed00-11d1-11ea-82bd-2862a1ca0e74.png)
![Screenshot from 2019-11-28 11-17-07](https://user-images.githubusercontent.com/30049228/69780702-fd13ed00-11d1-11ea-947b-e600a587ac83.png)
![Uploading Screenshot from 2019-11-28 11-17-24.png…]()
![Uploading Screenshot from 2019-11-28 11-25-51.png…]()
![Uploading Screenshot from 2019-11-28 11-26-08.png…]()

**Comment by monu2580** [comment]
![Screenshot from 2019-11-28 11-11-19](https://user-images.githubusercontent.com/30049228/69780826-60058400-11d2-11ea-8cc2-6a9c80af33d4.png)
![Screenshot from 2019-11-28 11-14-26](https://user-images.githubusercontent.com/30049228/69780827-609e1a80-11d2-11ea-8cb6-94d4044be900.png)
![Screenshot from 2019-11-28 11-14-48](https://user-images.githubusercontent.com/30049228/69780828-609e1a80-11d2-11ea-88d9-e30841e6499c.png)
![Screenshot from 2019-11-28 11-16-56](https://user-images.githubusercontent.com/30049228/69780829-609e1a80-11d2-11ea-81cc-73776bca7615.png)
![Screenshot from 2019-11-28 11-17-07](https://user-images.githubusercontent.com/30049228/69780830-6136b100-11d2-11ea-9ae7-5f3c14b271fe.png)
![Screenshot from 2019-11-28 11-17-24](https://user-images.githubusercontent.com/30049228/69780831-6136b100-11d2-11ea-8d37-72c3ff5e9763.png)
![Screenshot from 2019-11-28 11-25-51](https://user-images.githubusercontent.com/30049228/69780832-6136b100-11d2-11ea-86ac-90846383432b.png)
![Screenshot from 2019-11-28 11-26-08](https://user-images.githubusercontent.com/30049228/69780834-6136b100-11d2-11ea-9832-323222ceb97f.png)
![Screenshot from 2019-11-28 11-33-52](https://user-images.githubusercontent.com/30049228/69781065-ffc31200-11d2-11ea-936d-760c3d840a9b.png)

**Comment by halcwb** [comment]
So, I tried about everthing in this thread:

- uninstalled the global webpack, using only local install
- updated to the latest versions
- linked webpack and webpack-cli

No luck!! Only directly running with ` node node_modules/webpack-dev-server/bin/webpack-dev-server.js` works.

Maybe a bug with > 91 comments is an indication??

**Comment by evilebottnawi** [comment]
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

If somebody faced with the problem again please open the new issue with reproducible example, I think we fixed it (please use `webpack-cli@4`)

**Comment by isaldarriaga** [comment]
i was able to solve this problem in fedora 33 this way:

1. install [nvm](https://github.com/nvm-sh/nvm)
2. `nvm install 10.23.3 # node version!`
3. `cd <your node path>`
2. `rm -Rf node_modules/`
3. `gedit package.json`
4. Add `"webpack": "^4.39.3"` to `"devDependencies"`
5. `npm install`
6. `npm start`
